# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Http Client CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        jdk-distribution: [temurin]
        jdk-version: [11]
    steps:
    - name: Configure runner - Linux 
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
        sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
    - name: Configure Runner - Windows
      if: contains(matrix.os, 'windows')
      run: |
        echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
      shell: cmd
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.jdk-distribution }}
        java-version: ${{ matrix.jdk-version }}
    - name: Run Tests
      run: mvn -ntp -U -B -fae clean install -pl :wildfly-http-naming-client -am -Dtest=SimpleNamingOperationTestCase#testHttpNamingEjbObjectResolverHelper -DfailIfNoTests=false
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: surefire-${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'
